export const fieldsObj = {
  data: [
    {
      index: "A",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "B",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "C",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "D",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "E",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "F",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "G",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "H",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "I",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
    {
      index: "J",
      startingValue: 3,
      valueChanged: [],
      statusOfChange: "",
      submitedValues: [],
    },
  ],
};
